const test = [
  {
    created_dt: "",
    data_source_modified_dt: "",
    entity_type: "",
    operating_status: "",
    legal_name: "",
    dba_name: "",
    physical_address: "",
    p_street: "",
    p_city: "",
    p_state: "",
    p_zip_code: "",
    phone: "",
    mailing_address: "",
    m_street: "",
    m_city: "",
    m_state: "",
    m_zip_code: "",
    usdot_number: "",
    mc_mx_ff_number: "",
    power_units: "",
    mcs_150_form_date: "",
    out_of_service_date: "",
    state_carrier_id_number: "",
    duns_number: "",
    drivers: "",
    mcs_150_mileage_year: "",
    id: "",
    credit_score: "",
    record_status: "",
  },
];

// Hi man , I have a new project with that stack : react js , vite , typescript , material ui , tanstack query

// I have the data as a csv file and that is the data shape
//  {
//     created_dt: "",
//     data_source_modified_dt: "",
//     entity_type: "",
//     operating_status: "",
//     legal_name: "",
//     dba_name: "",
//     physical_address: "",
//     p_street: "",
//     p_city: "",
//     p_state: "",
//     p_zip_code: "",
//     phone: "",
//     mailing_address: "",
//     m_street: "",
//     m_city: "",
//     m_state: "",
//     m_zip_code: "",
//     usdot_number: "",
//     mc_mx_ff_number: "",
//     power_units: "",
//     mcs_150_form_date: "",
//     out_of_service_date: "",
//     state_carrier_id_number: "",
//     duns_number: "",
//     drivers: "",
//     mcs_150_mileage_year: "",
//     id: "",
//     credit_score: "",
//     record_status: "",
//   },
